"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { useApp } from "../application/AppProvider";
import { AppButton, Badge, Toggle } from "../application/ui";

const SECTIONS = ["Interface", "Accessibility", "Audio", "Gameplay", "Privacy", "Data & Sync", "Account"] as const;
type Section = typeof SECTIONS[number];

export function SettingsScreen() {
  const router = useRouter();
  const { settings, setSettings, authUser, syncStatus, authError, storageHealth, signOutAccount, syncNow, changePassword, deleteAccount } = useApp();
  const [section, setSection] = useState<Section>("Interface");
  const [currentPassword, setCurrentPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmation, setConfirmation] = useState("");
  const [accountError, setAccountError] = useState("");
  const [accountBusy, setAccountBusy] = useState(false);
  const clearLocalProfile = () => { if (window.confirm("Delete all Bakugan TCG Online data stored in this browser?")) { localStorage.clear(); sessionStorage.clear(); window.location.reload(); } };
  const submitPassword = async (event: React.FormEvent) => { event.preventDefault(); setAccountBusy(true); setAccountError(""); try { await changePassword(currentPassword, newPassword); setCurrentPassword(""); setNewPassword(""); } catch (error) { setAccountError(error instanceof Error ? error.message : "Could not change password."); } finally { setAccountBusy(false); } };
  const removeAccount = async () => { setAccountBusy(true); setAccountError(""); try { await deleteAccount(confirmation); } catch (error) { setAccountError(error instanceof Error ? error.message : "Could not delete account."); } finally { setAccountBusy(false); } };
  const storageTitle = storageHealth.status === "error" ? "Latest changes not saved" : storageHealth.status === "saved" ? "Saved on this device" : "Local storage ready";

  return <>
    <section className="compact-page-heading"><div><span className="eyebrow">CLIENT PREFERENCES</span><h1>Settings</h1><p>Control the interface, accessibility, privacy, local storage, cloud sync, and account.</p></div></section>
    <section className="settings-layout-v2">
      <nav className="settings-section-nav panel" aria-label="Settings sections">{SECTIONS.map((item) => <button className={section === item ? "active" : ""} key={item} onClick={() => setSection(item)}>{item}</button>)}</nav>
      <main className="settings-content panel">
        {section === "Interface" && <><h2>Interface</h2><p className="settings-intro">Adjust how cards and general application elements are displayed.</p><label className="range-setting"><span>Card scale <b>{settings.cardScale}%</b></span><input type="range" min="80" max="140" value={settings.cardScale} onChange={(event) => setSettings({ ...settings, cardScale: Number(event.target.value) })}/></label></>}
        {section === "Accessibility" && <><h2>Accessibility</h2><Toggle label="Reduced motion" copy="Replace camera moves and flashes with static emphasis." checked={settings.reducedMotion} onChange={(value) => setSettings({ ...settings, reducedMotion: value })}/><Toggle label="High contrast" copy="Increase panel, border, and focus contrast." checked={settings.highContrast} onChange={(value) => setSettings({ ...settings, highContrast: value })}/></>}
        {section === "Audio" && <><h2>Audio</h2><Toggle label="Interface and match audio" copy="Phase calls, priority, and result cues." checked={settings.sound} onChange={(value) => setSettings({ ...settings, sound: value, soundEnabled: value })}/></>}
        {section === "Gameplay" && <><h2>Gameplay preferences</h2><label>Default match-log detail<select value={settings.logDetail} onChange={(event) => setSettings({ ...settings, logDetail: event.target.value })}><option>All events</option><option>Gameplay only</option><option>Random results</option></select></label><p className="settings-note">These preferences affect supporting information around matches. The Match screen layout itself is unchanged by this overhaul.</p></>}
        {section === "Privacy" && <><h2>Privacy</h2><Toggle label="Allow match-record links" copy="Enable copyable links to locally retained completed match records." checked={settings.replayLinks ?? true} onChange={(value) => setSettings({ ...settings, replayLinks: value })}/><p className="settings-note">Friend challenges and block management are not shown until supporting social services exist.</p></>}
        {section === "Data & Sync" && <><div className="settings-title-row"><div><h2>{authUser ? "Cloud sync" : "Local storage"}</h2><p>{authUser ? "Sync durable account data between signed-in devices." : "Your decks, records, and settings are stored in this browser."}</p></div><Badge tone={syncStatus === "synced" || storageHealth.status === "saved" ? "gold" : syncStatus === "error" || storageHealth.status === "error" ? "red" : "blue"}>{authUser ? syncStatus.toUpperCase() : storageHealth.status.toUpperCase()}</Badge></div>{authUser ? <><div className="settings-callout"><strong>{authUser.email}</strong><span>Decks, drafts, records, settings, and deck preferences sync after changes settle. Searches, replay position, room codes, active matches, and device identity remain device-local.</span></div>{authError && syncStatus === "error" && <p className="error-message">{authError}</p>}<div className="hero-actions"><AppButton tone="blue" onClick={syncNow}>SYNC NOW</AppButton><AppButton tone="ghost" onClick={() => void signOutAccount()}>LOG OUT</AppButton></div></> : <><div className={`settings-callout ${storageHealth.status === "error" ? "storage-failed" : ""}`}><strong>{storageTitle}</strong><span>{storageHealth.message}{storageHealth.savedAt ? ` Last successful save: ${new Date(storageHealth.savedAt).toLocaleString()}.` : ""}</span></div><AppButton tone="red" onClick={() => router.push("/")}>SIGN UP OR LOG IN TO SYNC</AppButton></>}</>}
        {section === "Account" && <><h2>Account</h2>{authUser ? <><div className="settings-callout"><strong>{authUser.email}</strong><span>Signed in to the Bakugan Battle Planet Online account service.</span></div><form className="password-form" onSubmit={submitPassword}><h3>Change password</h3><label>Current password<input type="password" autoComplete="current-password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} required/></label><label>New password<input type="password" autoComplete="new-password" minLength={10} maxLength={128} value={newPassword} onChange={(event) => setNewPassword(event.target.value)} required/></label><AppButton type="submit" tone="ghost" disabled={accountBusy}>UPDATE PASSWORD</AppButton></form><section className="danger-zone-v2"><h3>Danger zone</h3><div><h4>Delete cloud account</h4><p>This removes the cloud account and synced copy. The local browser copy remains until deleted separately.</p><label>Type DELETE to confirm<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)}/></label><button className="danger-text" disabled={accountBusy || confirmation.toUpperCase() !== "DELETE"} onClick={() => void removeAccount()}>DELETE CLOUD ACCOUNT</button></div><div><h4>Delete local browser data</h4><p>Remove all locally stored decks, records, settings, drafts, and active state from this browser.</p><button className="danger-text" onClick={clearLocalProfile}>DELETE LOCAL BROWSER DATA</button></div></section></> : <><p>Sign in to manage a cloud account, password, and synced data.</p><AppButton tone="red" onClick={() => router.push("/")}>SIGN UP OR LOG IN</AppButton><section className="danger-zone-v2"><h3>Danger zone</h3><div><h4>Delete local browser data</h4><p>Remove all locally stored decks, records, settings, drafts, and active state from this browser.</p><button className="danger-text" onClick={clearLocalProfile}>DELETE LOCAL BROWSER DATA</button></div></section></>}{accountError && <p className="error-message" role="alert">{accountError}</p>}</>}
      </main>
    </section>
  </>;
}
